### ISSUE TITLE
Request: Allow get_proc_address calls with user provided null-terminated strings

### ISSUE THREAD

**Issue by Lokathor** [glowcoil/raw-gl-context#1]
It would be very nice if `get_proc_address` had an alternate version where the user provides a string that's already a null terminated string (eg: `*const u8`), and then the intermediate allocations for the function name pointer can be avoided that way.

**Comment by micahrj** [comment]
Appreciate the suggestion! It doesn't really feel worth complicating the API surface to me, though, given that macOS expects the string as Unicode anyway.

**Comment by Lokathor** [comment]
Do you mean utf-8? Because all ASCII null-terminated strings are already utf-8 compatible.

And it would still be a good benefit on non-mac platforms

**Comment by micahrj** [comment]
I can see the argument for it, but I put a lot of value on keeping the API simple and safe, and this doesn't feel worth it to me. But again, I appreciate the suggestion.
